name: GitHub Profile Views Counter CI

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  release:
    name: GitHub Profile Views Counter Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.INSIGHTS_TOKEN }}

      - name: Install dependencies for node-canvas
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install chartjs-node-canvas-cli
        run: npm install -g chartjs-node-canvas-cli

      - name: Generate chart
        run: |
          mkdir -p graph/416882051/large
          npx chartjs-node-canvas-cli \
            --type=line \
            --width=400 \
            --height=400 \
            --labels='["2025/7","2025/8","2025/9","2025/10","2025/11","2026/0","2026/1","2026/2","2026/3","2026/4","2026/5","2026/6","2026/7"]' \
            --datasets='[{"label":"Unique","data":[1,1,1,5,9,6,7,5,2,1,4,1,5],"backgroundColor":"#00a1c1","borderColor":"#008bad"},{"label":"Count","data":[1,2,1,5,34,6,11,12,4,1,7,1,10],"backgroundColor":"#00ffff","borderColor":"#00e7f2"}]' \
            --output='./graph/416882051/large/year.png'

      - uses: gayanvoice/github-profile-views-counter-action@3.0.0
        env:
          INSIGHTS_TOKEN: ${{ secrets.INSIGHTS_TOKEN }}
