name: GitHub Profile Views Counter CI

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  release:
    name: GitHub Profile Views Counter Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.INSIGHTS_TOKEN }}

      - name: Install dependencies for node-canvas
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: gayanvoice/github-profile-views-counter-action@3.0.0
        env:
          INSIGHTS_TOKEN: ${{ secrets.INSIGHTS_TOKEN }}
